# Generated by Django 3.2.7 on 2021-09-07 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyModelBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('emptymodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='common.emptymodelbase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('mturk_worker_id', models.CharField(blank=True, max_length=127)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True)),
            ],
            bases=('common.emptymodelbase',),
        ),
        migrations.CreateModel(
            name='ExperimentWorker',
            fields=[
                ('emptymodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.emptymodelbase')),
                ('tutorial_completed', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_workers', to='common.userprofile')),
            ],
            bases=('common.emptymodelbase',),
        ),
    ]
