# Generated by Django 3.2.7 on 2021-09-08 01:40

from django.db import migrations, models
import django.db.models.deletion
import mturk.utils


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentInstance',
            fields=[
                ('emptymodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.emptymodelbase')),
                ('reward', models.DecimalField(decimal_places=4, max_digits=8)),
                ('external_url', models.CharField(max_length=255)),
                ('num_outputs_max', models.IntegerField(default=5)),
                ('contents_per_hit', models.IntegerField(default=1)),
                ('frame_height', models.IntegerField(default=800)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(max_length=1000)),
                ('duration', models.IntegerField(default=3600)),
                ('lifetime', models.IntegerField(default=432000)),
                ('auto_approval_delay', models.IntegerField(default=172800)),
                ('qualifications', models.TextField(default='{}')),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            bases=('common.emptymodelbase',),
        ),
        migrations.CreateModel(
            name='MtHit',
            fields=[
                ('emptymodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='common.emptymodelbase')),
                ('mturk_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('hit_type', models.CharField(blank=True, max_length=128)),
                ('lifetime', models.IntegerField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('sandbox', models.BooleanField(default=mturk.utils.is_mturk_sandbox)),
                ('any_submitted_assignments', models.BooleanField(default=False)),
                ('all_submitted_assignments', models.BooleanField(default=False)),
                ('max_assignments', models.IntegerField(default=1)),
                ('num_assignments_available', models.IntegerField(blank=True, null=True)),
                ('num_assignments_completed', models.IntegerField(blank=True, null=True)),
                ('num_assignments_pending', models.IntegerField(blank=True, null=True)),
                ('hit_status', models.CharField(blank=True, choices=[('A', 'Assignable'), ('U', 'Unassignable'), ('R', 'Reviewable'), ('E', 'Reviewing'), ('D', 'Disposed')], max_length=1, null=True)),
                ('experiment_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='common.experimentinstance')),
            ],
            options={
                'verbose_name': 'HIT',
                'verbose_name_plural': 'HITs',
            },
            bases=('common.emptymodelbase',),
        ),
        migrations.CreateModel(
            name='MtExperiment',
            fields=[
                ('emptymodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.emptymodelbase')),
                ('slug', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('has_tutorial', models.BooleanField(default=False)),
                ('template_dir', models.CharField(default='mturk/experiments', max_length=255)),
                ('new_hit_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='common.experimentinstance')),
            ],
            bases=('common.emptymodelbase',),
        ),
        migrations.CreateModel(
            name='MtAssignment',
            fields=[
                ('emptymodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='common.emptymodelbase')),
                ('mturk_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('accept_time', models.DateTimeField(blank=True, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('approval_time', models.DateTimeField(blank=True, null=True)),
                ('rejection_time', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('auto_approval_time', models.DateTimeField(blank=True, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bonus_message', models.TextField(blank=True)),
                ('approve_message', models.TextField(blank=True)),
                ('reject_message', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('screen_width', models.IntegerField(blank=True, null=True)),
                ('screen_height', models.IntegerField(blank=True, null=True)),
                ('post_data', models.TextField(blank=True)),
                ('post_meta', models.TextField(blank=True)),
                ('time_ms', models.IntegerField(blank=True, null=True)),
                ('time_active_ms', models.IntegerField(blank=True, null=True)),
                ('time_load_ms', models.IntegerField(blank=True, null=True)),
                ('wage', models.FloatField(blank=True, null=True)),
                ('submission_complete', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('S', 'Submitted'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1, null=True)),
                ('hit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='common.mthit')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='common.userprofile')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
            },
            bases=('common.emptymodelbase',),
        ),
        migrations.AddField(
            model_name='experimentworker',
            name='experiment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='experiment_workers', to='common.mtexperiment'),
            preserve_default=False,
        ),
    ]
