# Generated by Django 3.2.7 on 2021-09-08 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210908_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtexperiment',
            old_name='slug',
            new_name='experiment_slug',
        ),
        migrations.AddField(
            model_name='experimentinstance',
            name='experiment_instance_slug',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mthit',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='common.mtexperiment'),
        ),
    ]
