# Generated by Django 3.2.7 on 2021-09-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_experimentinstance_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mthit',
            name='hit_type',
        ),
        migrations.AddField(
            model_name='experimentinstance',
            name='hit_type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
