# Generated by Django 3.2.7 on 2021-09-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210908_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtexperiment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mtexperiment',
            name='template_dir',
        ),
    ]
