# Generated by Django 3.2.7 on 2021-09-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210909_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mturk_worker_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emptymodelbase_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.emptymodelbase'),
        ),
    ]
