# Generated by Django 3.2.7 on 2021-09-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_mtassignment_experiment_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtassignment',
            name='time_active_ms',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mtassignment',
            name='time_load_ms',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mtassignment',
            name='time_ms',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mtassignment',
            name='wage',
            field=models.FloatField(default=0, null=True),
        ),
    ]
