# Generated by Django 3.2.7 on 2021-09-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_mtassignment_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtassignment',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='common.mtexperiment'),
        ),
        migrations.AddField(
            model_name='mtassignment',
            name='experiment_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='common.experimentinstance'),
        ),
    ]
