# Generated by Django 3.2.7 on 2021-09-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_mthit_workers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentinstance',
            old_name='assignemnts',
            new_name='num_assignments',
        ),
    ]
