# Generated by Django 3.2.7 on 2021-09-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_rename_assignemnts_experimentinstance_num_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentinstance',
            old_name='hit_type',
            new_name='hit_type_production',
        ),
        migrations.AddField(
            model_name='experimentinstance',
            name='hit_type_sandbox',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
