# Generated by Django 3.2.7 on 2021-09-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210910_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentinstance',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8),
        ),
    ]
